routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*********************Front**********************/

Auth::routes(['register' => false]);

Route::get('/', 'HomeController@index')->name('home');
Route::get('/page/{slug}-{id}', 'HomeController@page')->name('page')->where(['slug' => '[A-Za-z0-9_\-]+','id' => '\d+']);
Route::get('/offers/{slug}-{offer_id}', 'HomeController@offers')->name('offers')->where(['slug' => '[A-Za-z0-9_\-]+','id' => '\d+']);
Route::get('/leaflets', 'HomeController@leaflet')->name('leaflet');
Route::get('/leaflets/{slug}', 'HomeController@leafletGet')->name('leaflet.Get');

Route::post('/form/ad', 'BravoFormController@addReklamForm')->name('form.ad');
Route::post('/form/media', 'BravoFormController@addMediaForm')->name('form.media');
Route::post('/form/b2b', 'BravoFormController@addB2bForm')->name('form.b2b');
Route::post('/form/supplier', 'BravoFormController@addSupplierForm')->name('form.supplier');
Route::post('/form/contact_feedback', 'BravoFormController@addContactFeedback')->name('form.contact_feedback');
Route::post('/form/customer_feedback', 'BravoFormController@addCustomerFeedback')->name('form.customer_feedback');


Route::get('/language/{language?}', 'HomeController@setLocale')->name('setLocale');

Route::group(['prefix' => 'career', 'as' => 'career.'],function (){
    Route::get('/', 'CareerController@index')->name('index');
    Route::get('/apply', 'CareerController@applyGet')->name('applyGet');
    Route::post('/apply', 'CareerController@applyStore')->name('applyStore');
});

Route::get('/cards', 'HomeController@card')->name('card');
Route::get('/page/students/{group_id}', 'HomeController@getStudentsWithGroup')->name('get.students.group');

Route::get('/v1/api/stores', 'HomeController@getAllStores')->name('api.stores');
Route::get('/v1/api/store/{id}', 'HomeController@getStoreById')->name('api.store');
Route::get('/v1/api/search/store', 'HomeController@searchStore')->name('api.store.search');



/*********************Panel**********************/
Route::group(['prefix' => 'admin', 'middleware' => ['auth','lang'], 'as' => 'admin.'],function(){
    Route::get('/', 'AdminController@index')->name('dashboard');



    //Rauf Abbas
    Route::delete('/vacancies/deleteSelecteds', 'BannerController@destroySelecteds');
    Route::resource('/vacancies', 'VacancyController');
    Route::get('/vacancies/export/{id}', 'VacancyController@export')->name('vacancies.export');

    Route::delete('/cards/deleteSelecteds', 'CardController@destroySelecteds');
    Route::resource('/cards', 'CardController');

    Route::delete('/stores/deleteSelecteds', 'StoreController@destroySelecteds');
    Route::resource('/stores', 'StoreController');

    Route::delete('/students/deleteSelecteds', 'StudentController@destroySelecteds');
    Route::resource('/students', 'StudentController');


    Route::resource('/leaflets', 'LeafletController');
    Route::delete('/leaflets/deleteSelecteds', 'LeafletController@destroySelecteds');


    Route::delete('/categories/deleteSelecteds', 'CategoryController@destroySelecteds');
    Route::resource('/categories', 'CategoryController');

    Route::delete('/posts/deleteSelecteds', 'PostController@destroySelecteds');
    Route::resource('/posts', 'PostController');

    Route::resource('/tabs/deleteSelecteds', 'TabController@destroySelecteds');
    Route::resource('/tabs', 'TabController');

    Route::delete('/faqs/deleteSelecteds', 'FaqController@destroySelecteds');
    Route::resource('/faqs', 'FaqController');

    Route::delete('/menus/deleteSelecteds', 'MenuController@destroySelecteds');
    Route::resource('/menus', 'MenuController');

    Route::delete('/pages/deleteSelecteds', 'PageController@destroySelecteds');
    Route::resource('/pages', 'PageController');

    Route::delete('/sliders/deleteSelecteds', 'SliderController@destroySelecteds');
    Route::resource('/sliders', 'SliderController');

    Route::delete('/banners/deleteSelecteds', 'BannerController@destroySelecteds');
    Route::resource('/banners', 'BannerController');

    Route::delete('/offers/deleteSelecteds', 'OfferController@destroySelecteds');
    Route::resource('/offers', 'OfferController');

    Route::delete('/offers/deleteSelecteds', 'OfferProductController@destroySelecteds');
    Route::resource('/offer-products', 'OfferProductController');

    Route::delete('/users/deleteSelecteds', 'UserController@destroySelecteds');
    Route::resource('/users', 'UserController');

    Route::delete('/roles/deleteSelecteds', 'RoleController@destroySelecteds');
    Route::resource('/roles', 'RoleController');

    Route::delete('/permissions/deleteSelecteds', 'PermissionController@destroySelecteds');
    Route::resource('/permissions', 'PermissionController');

    Route::delete('/languages/deleteSelecteds', 'LanguageController@destroySelecteds');
    Route::resource('/languages', 'LanguageController');

    Route::get('/translation_group/{translation_group}/translations', 'TranslationGroupController@translations')->name('translation_group.translations');
    Route::delete('/translation_groups/deleteSelecteds', 'TranslationGroupController@destroySelecteds');
    Route::resource('/translation_groups', 'TranslationGroupController');

    Route::get('/translations/exportView', 'TranslationController@exportView')->name('translations.exportView');
    Route::get('/translations/export', 'TranslationController@export')->name('translations.export');
    Route::get('/translations/create/{group?}', 'TranslationController@create');
    Route::delete('/translations/deleteSelecteds', 'TranslationController@destroySelecteds');
    Route::resource('/translations', 'TranslationController');

    Route::post('/mediaUpload', 'AdminController@mediaUpload')->name('mediaUpload');
    Route::post('/generateSlug', 'AdminController@generateSlug')->name('generateSlug');
    Route::post('/generateOrderNumberInParent', 'AdminController@generateOrderNumberInParent')->name('generateOrderNumberInParent');
    Route::post('/reorder', 'AdminController@reorder')->name('reorder');

    Route::get('/config', 'AdminController@index')->name('config');
    Route::get('/site', 'AdminController@index')->name('site');

    Route::get('/requests/{type}', 'BravoFormController@getAdminPanel')->name('requests.index');
});

app/Card.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Card extends Model
{
    public function author(){
        return $this->belongsTo('\App\User','author_id','id');
    }

    public function media(){
        return $this->belongsTo('\Botble\Media\Models\MediaFile','media_id','id');
    }
}

app/Http/Controllers/CardController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Language;
use App\Card;
use App\Post;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CardController extends Controller
{

    public function __construct()
    {
        $this->middleware('permission:create-cards', ['only' => ['create', 'store']]);
        $this->middleware('permission:read-cards'  , ['only' => ['index']]);
        $this->middleware('permission:update-cards', ['only' => ['edit','update']]);
        $this->middleware('permission:delete-cards', ['only' => ['destroy','destroySelecteds']]);
    }

    public function index()
    {
        $cards = Card::with('author')
            ->where('locale',getLocale())
            ->orderBy('created_at','desc')
            ->get();

        return view('admin.cards.index',compact('cards'));

    }


    public function create()
    {
        return view('admin.cards.create');
    }


    public function store(Request $request)
    {

        $request->validate([
            'title' => 'required|array|check_array:1',
            'title.*' => 'string|nullable',
            'slug' => 'required|array|check_array:1|unique:posts',
            'slug.*' => 'string|nullable',
            'content' => 'required|array|check_array:1',
            'content.*' => 'string|nullable',
        ]);


        $card_id = uniqid();
        foreach (getLocales() as $locale){
            $card = new Card();
            $card->card_id = $card_id;
            $card->locale = $locale;
            $card->author_id = user()->id;
            $card->title = $request->title[$locale];
            $card->content = $request->get('content')[$locale];
            $card->slug = $request->slug[$locale];
            $card->media_id = $request->media[0];
            $card->date = dbDate($request->date);
            $card->status = $request->status == 'on' ? true : false;
            $card->save();
        }

        $data = [
            'status'    => 'success',
            'message'   => "Card <code>{$request->title[getLocale()]}</code> is created successfully"
        ];
        return response()->json($data,200);
    }


    public function show(Post $post)
    {
        //
    }


    public function edit($card_id)
    {
        $card_data = Card::with('media')->where('card_id',$card_id)->get();
        $cards = [];
        foreach ($card_data as $card){
            $cards[$card->locale] = $card;
        }
        return view('admin.cards.edit',compact('cards'));
    }


    public function update(Request $request, $card_id)
    {
        $cards = Card::where('card_id',$card_id)->get();
        $slug_validaiton = '';
        foreach ($cards as $Card) {
            $slug_validaiton .= '|unique:posts,slug,'.$Card->id;
        }
        $request->validate([
            'title' => 'required|array|check_array:1',
            'title.*' => 'string|nullable',
            'slug' => 'required|array|check_array:1'.$slug_validaiton,
            'slug.*' => 'string|nullable',
            'content' => 'required|array|check_array:1',
            'content.*' => 'string|nullable',
        ]);


        foreach (getLocales() as $locale){
            $card = Card::where('card_id',$card_id)->where('locale',$locale)->first();
            if(!$card){ // eger bu dilde post yoxdursa yenisini yaradir
                $card = new Card();
                $card->card_id = $card_id;
                $card->locale = $locale;
                $card->author_id = user()->id;
            }
            $card->title = $request->title[$locale];
            $card->slug = $request->slug[$locale];
            $card->media_id = $request->media[0];
            $card->content = $request->get('content')[$locale];
            $card->status = $request->status == 'on' ? true : false;
            $card->date = dbDate($request->date);

            $card->save();
        }

        $data = [
            'status'    => 'success',
            'message'   => "Card <code>{$request->title[getLocale()]}</code> is updated successfully"
        ];
        return response()->json($data,200);
    }


    public function destroy(Card $card)
    {
        $oldData = $card->title;
        $card->delete();

        $data = [
            'status'    => 'success',
            'message'   => "Card - <span class='font-weight-semibold'>{$oldData}</span> is deleted successfully!"
        ];
        return response()->json($data,200);
    }

    public function destroySelecteds(Request $request)
    {
        foreach ($request->selecteds as $selected) {
            $deleteData = Card::where('card_id',$selected)->first();
            $deleteData->delete();
        }

        $data = [
            'status'    => 'success',
            'message'   => "Selected <span class='font-weight-semibold'>Card</span> are deleted successfully!"
        ];
        return response()->json($data,200);
    }

}

resources/views/admin/cards/create.blade.php
@extends('admin.layouts.layout')


@section('styles')
    <style>

    </style>
@endsection

@section('content')

    <!-- Page header -->
    <div class="page-header page-header-light" style="border-left: 1px solid #ddd; border-right: 1px solid #ddd;">

        <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline py-2">
            <div class="d-flex">
                <div class="breadcrumb">
                    <a href="{{route('admin.dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> {{translate('breadcrumb.dashboard')}}</a>
                    <a href="{{route('admin.cards.index')}}" class="breadcrumb-item">{{translate('breadcrumb.cards')}}</a>
                    <span class="breadcrumb-item active">{{translate('breadcrumb.newVacancy')}}</span>
                </div>
            </div>
        </div>
    </div>
    <!-- /page header -->

    <div class="content p-0">
        <form action="{{route('admin.cards.store')}}" method="post" data-reload="{{route('admin.cards.index')}}">
            @csrf
            <div class="card border-top-0 mb-0 border-x-0">
                <div class="card-body px-0">


                    <ul class="nav nav-tabs nav-tabs-highlight">
                        @foreach(getLanguages() as $language)
                            <li class="nav-item"><a href="#tab-{{$language['key']}}" class="nav-link {{getLocale()===$language['key']?'active':''}}" data-toggle="tab">{{$language['name']}}</a></li>
                        @endforeach
                            <li class="nav-item"><a href="#tab-gallery" class="nav-link" data-toggle="tab">{{translate('tabs.gallery')}}</a></li>
                            <li class="nav-item"><a href="#tab-settings" class="nav-link" data-toggle="tab">{{translate('tabs.settings')}}</a></li>
                    </ul>


                    <div class="tab-content px-3">
                        @foreach(getLanguages() as $language)
                            <div class="tab-pane fade {{getLocale()===$language['key']?'active show':''}}" id="tab-{{$language['key']}}">
                                <div class="row">
                                    <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                        <label for="title-{{$language['key']}}"><i class="icon-pencil5 title-icon"></i>{{translate('cards.title')}}</label>
                                        <input class="form-control" id="title-{{$language['key']}}" name="title[{{$language['key']}}]">
                                        @if($errors->has('title'))
                                            <div class="text-danger">{{$errors->first('title')}}</div>
                                        @endif
                                    </div>

                                    <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                        <label for="content-{{$language['key']}}"><i class="icon-file-text title-icon"></i>{{translate('cards.content')}}</label>
                                        <textarea class="form-control post-content" id="content-{{$language['key']}}" name="content[{{$language['key']}}]"></textarea>
                                        @if($errors->has('content'))
                                            <div class="text-danger">{{$errors->first('content')}}</div>
                                        @endif
                                    </div>

                                    <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                        <label for="slug-{{$language['key']}}"><i class="icon-hyperlink title-icon"></i>{{translate('cards.slug')}}</label>
                                        <input class="form-control" id="slug-{{$language['key']}}" name="slug[{{$language['key']}}]">
                                        @if($errors->has('slug'))
                                            <div class="text-danger">{{$errors->first('slug')}}</div>
                                        @endif
                                    </div>

                                </div>
                            </div>
                        @endforeach
                            <div class="tab-pane fade" id="tab-gallery">
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <div class="btn bg-slate" id="openMediaManager"  data-media-select-type="single" data-media-title="true"><i class="icon-gallery"></i> {{translate('media.openMediaManager')}}</div>
                                        <div class="media-area row">
                                            <input type="hidden" id="media" name="media">
                                            <empty>
                                                <i class="icon-files-empty title-icon"></i>{{translate('common.nothingSelected')}}
                                            </empty>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="tab-settings">
                                <div class="row">
                                    <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                        <label for="date"><i class="icon-calendar3 title-icon"></i>{{translate('cards.date')}}</label>
                                        <div class="input-group">
                                            <input class="form-control" id="date" name="date">
                                        </div>
                                        @if($errors->has('date'))
                                            <div class="text-danger">{{$errors->first('date')}}</div>
                                        @endif
                                    </div>

                                    <div class="form-group col-lg-12 col-md-12 col-sm-12 pl-3">
                                        <label for="status"><i class="icon-file-check title-icon"></i>{{translate('cards.status')}}</label>
                                        <div class="input-group">
                                            <input class="form-control switchery" id="status" type="checkbox" name="status" checked>
                                        </div>
                                    </div>

                                </div>
                            </div>
                    </div>

                </div>

                <div class="card-footer">
                    <div class="text-right">
                        <button class="btn bg-slate submitAJAX">{{translate('users.addNewCard')}}</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

@endsection

@section('scripts')
    <script>
        {{--editör istifade etsez aşağıdakını istifade edin--}}
        // $('.post-content').each(function(){
        //     pashayev.editor($(this).attr('id'));
        // });
        pashayev.datePicker('#date');
        $('#category').select2();

        CKEDITOR.on('instanceReady', function(){
            $.each( CKEDITOR.instances, function(instance) {
                CKEDITOR.instances[instance].on("change", function(e) {
                    for ( instance in CKEDITOR.instances )
                        CKEDITOR.instances[instance].updateElement();
                });
            });
        });

        $(document).on('change','[id*=title]',function(){
            let text = $(this).val();
            let slugInput = $(this).parents('.row').find('[id*=slug]');
            $.post('{{route('admin.generateSlug')}}',{text},function(slug){
                slugInput.val(slug);
            })
        });
    </script>
@endsection

resources/views/admin/cards/edit.blade.php
@extends('admin.layouts.layout')


@section('styles')
    <style>

    </style>
@endsection

@section('content')

    <!-- Page header -->
    <div class="page-header page-header-light" style="border-left: 1px solid #ddd; border-right: 1px solid #ddd;">

        <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline py-2">
            <div class="d-flex">
                <div class="breadcrumb">
                    <a href="{{route('admin.dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> {{translate('breadcrumb.dashboard')}}</a>
                    <a href="{{route('admin.cards.index')}}" class="breadcrumb-item">{{translate('breadcrumb.cards')}}</a>
                    <span class="breadcrumb-item active">{{$cards[getLocale()]->title}}</span>
                </div>
            </div>
        </div>
    </div>
    <!-- /page header -->

    @php
        $cardData = null;
        foreach ($cards as $card){$cardData = $card;}
    @endphp
    <div class="content p-0">
        <form action="{{route('admin.cards.update',['card' => $cardData->card_id])}}" method="post" data-reload="{{route('admin.cards.index')}}">
            @csrf
            @method('PUT')
            <div class="card border-top-0 mb-0 border-x-0">
                @if(session()->has('success'))
                    {!! alert(session()->get('success')) !!}
                @endif
                <div class="card-body px-0">
                    <ul class="nav nav-tabs nav-tabs-highlight">
                        @foreach(getLanguages() as $language)
                            <li class="nav-item"><a href="#tab-{{$language['key']}}" class="nav-link {{getLocale()===$language['key']?'active':''}}" data-toggle="tab">{{$language['name']}}</a></li>
                        @endforeach
                        <li class="nav-item"><a href="#tab-gallery" class="nav-link" data-toggle="tab">{{translate('tabs.gallery')}}</a></li>
                        <li class="nav-item"><a href="#tab-settings" class="nav-link" data-toggle="tab">{{translate('tabs.settings')}}</a></li>
                    </ul>


                    <div class="tab-content px-3">
                        @foreach(getLanguages() as $language)

                            @php($card = $cards[$language['key']]??null)
                            <div class="tab-pane fade {{getLocale()===$language['key']?'active show':''}}" id="tab-{{$language['key']}}">
                                <div class="row">
                                    <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                        <label for="title-{{$language['key']}}"><i class="icon-pencil5 title-icon"></i>{{translate('cards.title')}}</label>
                                        <input class="form-control" id="title-{{$language['key']}}" name="title[{{$language['key']}}]" value="{{$card->title??''}}">
                                        @if($errors->has('title'))
                                            <div class="text-danger">{{$errors->first('title')}}</div>
                                        @endif
                                    </div>


                                    <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                        <label for="content-{{$language['key']}}"><i class="icon-file-text title-icon"></i>{{translate('cards.content')}}</label>
                                        <textarea class="form-control post-content" id="content-{{$language['key']}}" name="content[{{$language['key']}}]">{{$card->content??''}}</textarea>
                                        @if($errors->has('content'))
                                            <div class="text-danger">{{$errors->first('content')}}</div>
                                        @endif
                                    </div>

                                    <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                        <label for="slug-{{$language['key']}}"><i class="icon-hyperlink title-icon"></i>{{translate('posts.slug')}}</label>
                                        <input class="form-control" id="slug-{{$language['key']}}" name="slug[{{$language['key']}}]" value="{{$card->slug??''}}">
                                        @if($errors->has('slug'))
                                            <div class="text-danger">{{$errors->first('slug')}}</div>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        @endforeach
                        <div class="tab-pane fade" id="tab-gallery">
                            <div class="row">
                                <div class="form-group col-lg-12 col-md-12 col-sm-6">
                                    <div class="btn bg-slate" id="openMediaManager"><i class="icon-gallery"></i> {{translate('media.openMediaManager')}}</div>
                                    <div class="media-area row">
                                        <empty class="d-none"><i class="icon-files-empty title-icon"></i>{{translate('common.nothingSelected')}}</empty>
                                        @if($card->media)
                                            <a href="{{$card->media->url}}" class="fancybox" data-fancybox="media">
                                                <div class="image" id="{{$card->media->id}}">
                                                    <img src="{{$card->media->url}}">
                                                    <div class="action deleteMedia">×</div>
                                                    <div class="action editMedia"><i class="icon-crop"></i></div>
                                                    <div class="action showMedia"><i class="icon-eye"></i></div>
                                                    <input type="hidden" name="media[]" value="{{$card->media->id}}">
                                                </div>
                                            </a>
                                        @endif
                                    </div>
                                </div>
                                >
                            </div>
                        </div>
                        <div class="tab-pane fade" id="tab-settings">
                            <div class="row">

                                <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                    <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                        <label for="date"><i class="icon-calendar3 title-icon"></i>{{translate('posts.date')}}</label>
                                        <div class="input-group">
                                            <input class="form-control" id="date" name="date" value="{{humanDate($cardData->date)}}">
                                        </div>
                                        @if($errors->has('date'))
                                            <div class="text-danger">{{$errors->first('date')}}</div>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group col-lg-12 col-md-12 col-sm-12 pl-3">
                                    <label for="status"><i class="icon-file-check title-icon"></i>{{translate('pages.status')}}</label>
                                    <div class="input-group">
                                        <input class="form-control switchery" id="status" type="checkbox" name="status" {{$cardData->status?'checked':''}}>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>

                <div class="card-footer">
                    <div class="text-right">
                        <button class="btn bg-slate submitAJAX">{{translate('users.updateCard')}}</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

@endsection

@section('scripts')
    <script>
        appendedMedias = [@json($cardData->media)];
        {{--editör istifade etsez aşağıdakını istifade edin--}}

        // $('.post-content').each(function(){
        //     pashayev.editor($(this).attr('id'));
        // });
        $('#date').daterangepicker({
            locale: {
                format: 'DD.MM.YYYY HH:mm:ss'
            },
            singleDatePicker: true,
            timePicker: true,
            startDate: moment(),
            timePicker24Hour: true,
            autoUpdateInput: false,
            autoApply: true
        },function(date){
            console.log(date)
            $('#date').val(date.format('DD.MM.YYYY HH:mm:ss'));
        });
        $("#date").data('daterangepicker').setStartDate($('#date').val());

        $('#category').select2();

        CKEDITOR.on('instanceReady', function(){
            $.each( CKEDITOR.instances, function(instance) {
                CKEDITOR.instances[instance].on("change", function(e) {
                    for ( instance in CKEDITOR.instances )
                        CKEDITOR.instances[instance].updateElement();
                });
            });
        });

        $(document).on('change','[id*=title]',function(){
            let text = $(this).val();
            let slugInput = $(this).parents('.row').find('[id*=slug]');
            $.post('{{route('admin.generateSlug')}}',{text},function(slug){
                slugInput.val(slug);
            })
        });
    </script>
@endsection