routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*********************Front**********************/

Auth::routes(['register' => false]);

Route::get('/', 'HomeController@index')->name('home');
Route::get('/page/{slug}-{id}', 'HomeController@page')->name('page')->where(['slug' => '[A-Za-z0-9_\-]+','id' => '\d+']);
Route::get('/offers/{slug}-{offer_id}', 'HomeController@offers')->name('offers')->where(['slug' => '[A-Za-z0-9_\-]+','id' => '\d+']);
Route::get('/leaflets', 'HomeController@leaflet')->name('leaflet');
Route::get('/leaflets/{slug}', 'HomeController@leafletGet')->name('leaflet.Get');

Route::post('/form/ad', 'BravoFormController@addReklamForm')->name('form.ad');
Route::post('/form/media', 'BravoFormController@addMediaForm')->name('form.media');
Route::post('/form/b2b', 'BravoFormController@addB2bForm')->name('form.b2b');
Route::post('/form/supplier', 'BravoFormController@addSupplierForm')->name('form.supplier');
Route::post('/form/contact_feedback', 'BravoFormController@addContactFeedback')->name('form.contact_feedback');
Route::post('/form/customer_feedback', 'BravoFormController@addCustomerFeedback')->name('form.customer_feedback');


Route::get('/language/{language?}', 'HomeController@setLocale')->name('setLocale');

Route::group(['prefix' => 'career', 'as' => 'career.'],function (){
    Route::get('/', 'CareerController@index')->name('index');
    Route::get('/apply', 'CareerController@applyGet')->name('applyGet');
    Route::post('/apply', 'CareerController@applyStore')->name('applyStore');
});

Route::get('/cards', 'HomeController@card')->name('card');
Route::get('/page/students/{group_id}', 'HomeController@getStudentsWithGroup')->name('get.students.group');

Route::get('/v1/api/stores', 'HomeController@getAllStores')->name('api.stores');
Route::get('/v1/api/store/{id}', 'HomeController@getStoreById')->name('api.store');
Route::get('/v1/api/search/store', 'HomeController@searchStore')->name('api.store.search');



/*********************Panel**********************/
Route::group(['prefix' => 'admin', 'middleware' => ['auth','lang'], 'as' => 'admin.'],function(){
    Route::get('/', 'AdminController@index')->name('dashboard');



    //Rauf Abbas
    Route::delete('/vacancies/deleteSelecteds', 'BannerController@destroySelecteds');
    Route::resource('/vacancies', 'VacancyController');
    Route::get('/vacancies/export/{id}', 'VacancyController@export')->name('vacancies.export');

    Route::delete('/cards/deleteSelecteds', 'CardController@destroySelecteds');
    Route::resource('/cards', 'CardController');

    Route::delete('/stores/deleteSelecteds', 'StoreController@destroySelecteds');
    Route::resource('/stores', 'StoreController');

    Route::delete('/students/deleteSelecteds', 'StudentController@destroySelecteds');
    Route::resource('/students', 'StudentController');


    Route::resource('/leaflets', 'LeafletController');
    Route::delete('/leaflets/deleteSelecteds', 'LeafletController@destroySelecteds');


    Route::delete('/categories/deleteSelecteds', 'CategoryController@destroySelecteds');
    Route::resource('/categories', 'CategoryController');

    Route::delete('/posts/deleteSelecteds', 'PostController@destroySelecteds');
    Route::resource('/posts', 'PostController');

    Route::resource('/tabs/deleteSelecteds', 'TabController@destroySelecteds');
    Route::resource('/tabs', 'TabController');

    Route::delete('/faqs/deleteSelecteds', 'FaqController@destroySelecteds');
    Route::resource('/faqs', 'FaqController');

    Route::delete('/menus/deleteSelecteds', 'MenuController@destroySelecteds');
    Route::resource('/menus', 'MenuController');

    Route::delete('/pages/deleteSelecteds', 'PageController@destroySelecteds');
    Route::resource('/pages', 'PageController');

    Route::delete('/sliders/deleteSelecteds', 'SliderController@destroySelecteds');
    Route::resource('/sliders', 'SliderController');

    Route::delete('/banners/deleteSelecteds', 'BannerController@destroySelecteds');
    Route::resource('/banners', 'BannerController');

    Route::delete('/offers/deleteSelecteds', 'OfferController@destroySelecteds');
    Route::resource('/offers', 'OfferController');

    Route::delete('/offers/deleteSelecteds', 'OfferProductController@destroySelecteds');
    Route::resource('/offer-products', 'OfferProductController');

    Route::delete('/users/deleteSelecteds', 'UserController@destroySelecteds');
    Route::resource('/users', 'UserController');

    Route::delete('/roles/deleteSelecteds', 'RoleController@destroySelecteds');
    Route::resource('/roles', 'RoleController');

    Route::delete('/permissions/deleteSelecteds', 'PermissionController@destroySelecteds');
    Route::resource('/permissions', 'PermissionController');

    Route::delete('/languages/deleteSelecteds', 'LanguageController@destroySelecteds');
    Route::resource('/languages', 'LanguageController');

    Route::get('/translation_group/{translation_group}/translations', 'TranslationGroupController@translations')->name('translation_group.translations');
    Route::delete('/translation_groups/deleteSelecteds', 'TranslationGroupController@destroySelecteds');
    Route::resource('/translation_groups', 'TranslationGroupController');

    Route::get('/translations/exportView', 'TranslationController@exportView')->name('translations.exportView');
    Route::get('/translations/export', 'TranslationController@export')->name('translations.export');
    Route::get('/translations/create/{group?}', 'TranslationController@create');
    Route::delete('/translations/deleteSelecteds', 'TranslationController@destroySelecteds');
    Route::resource('/translations', 'TranslationController');

    Route::post('/mediaUpload', 'AdminController@mediaUpload')->name('mediaUpload');
    Route::post('/generateSlug', 'AdminController@generateSlug')->name('generateSlug');
    Route::post('/generateOrderNumberInParent', 'AdminController@generateOrderNumberInParent')->name('generateOrderNumberInParent');
    Route::post('/reorder', 'AdminController@reorder')->name('reorder');

    Route::get('/config', 'AdminController@index')->name('config');
    Route::get('/site', 'AdminController@index')->name('site');

    Route::get('/requests/{type}', 'BravoFormController@getAdminPanel')->name('requests.index');
});

app/Language.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Language extends Model
{
    //
}

app/Http/Controllers/LanguageController.php
<?php

namespace App\Http\Controllers;

use App\Language;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;

class LanguageController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:create-languages', ['only' => ['create', 'store']]);
        $this->middleware('permission:read-languages'  , ['only' => ['index']]);
        $this->middleware('permission:update-languages', ['only' => ['edit','update']]);
        $this->middleware('permission:delete-languages', ['only' => ['destroy','destroySelecteds']]);

        $languages = Language::all();
        View::share(compact('languages'));
    }

    public function index()
    {
        return view('admin.languages.index');
    }


    public function create()
    {
        return view('admin.languages.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'key' => 'required|string|unique:languages',
            'name' => 'required|string',
            'description' => 'string',
            'order' => 'required|integer',
        ]);

        $language = new Language();
        $language->key = $request->key;
        $language->name = $request->name;
        $language->description = $request->description;
        $language->order = $request->order;
        $language->save();

        $data = [
            'status'    => 'success',
            'message'   => "Language - <span class='font-weight-semibold'>{$language->name}</span> is created successfully!"
        ];
        return response()->json($data,200);
    }


    public function show(Language $language)
    {
        //
    }


    public function edit(Language $language)
    {
        return view('admin.languages.edit')->with(compact('language'));
    }


    public function update(Request $request, Language $language)
    {
        $request->validate([
            'key' => 'required|string',
            'name' => 'required|string',
            'description' => 'string',
            'order' => 'required|integer',
        ]);

        $oldData = $language->name;
        $language->key = $request->key;
        $language->name = $request->name;
        $language->description = $request->description;
        $language->order = $request->order;
        $language->status = $request->status?true:false;
        $language->save();

        $data = [
            'status'    => 'success',
            'message'   => "Language - <span class='font-weight-semibold'>{$oldData}</span> is updated successfully!"
        ];
        return response()->json($data,200);
    }

    public function destroy(Language $language)
    {
        $oldData = $language->name;
        $language->delete();

        $data = [
            'status'    => 'success',
            'message'   => "Language - <span class='font-weight-semibold'>{$oldData}</span> is deleted successfully!"
        ];
        return response()->json($data,200);
    }

    public function destroySelecteds(Request $request)
    {
        foreach ($request->selecteds as $selected) {
            $deleteData = Language::findOrFail($selected);
            $deleteData->delete();
        }

        $data = [
            'status'    => 'success',
            'message'   => "Selected <span class='font-weight-semibold'>languages</span> are deleted successfully!"
        ];
        return response()->json($data,200);
    }
}

resources/views/admin/languages/create.blade.php
@extends('admin.layouts.layout')


@section('styles')
    <style>
        #roles tr, #roles td, #roles th{
            border:1px solid #ebebeb;
            padding: 10px;
        }
        .select2-selection--multiple .select2-search--inline:first-child .select2-search__field {
            padding-left: .5rem;
        }
    </style>
@endsection

@section('content')

    <!-- Page header -->
    <div class="page-header page-header-light" style="border-left: 1px solid #ddd; border-right: 1px solid #ddd;">

        <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline py-2">
            <div class="d-flex">
                <div class="breadcrumb">
                    <a href="{{route('admin.dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> {{translate('breadcrumb.dashboard')}}</a>
                    <a href="{{route('admin.languages.index')}}" class="breadcrumb-item">{{translate('breadcrumb.languages')}}</a>
                    <span class="breadcrumb-item active">{{translate('breadcrumb.newLanguage')}}</span>
                </div>
            </div>
        </div>
    </div>
    <!-- /page header -->

    <div class="content p-0">
        <form action="{{route('admin.languages.store')}}" method="post" data-reload="reload">
            @csrf
            <div class="card border-top-0 mb-0">
                <div class="card-body">
                    <div class="row">

                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="key">{{translate('languages.key')}}</label>
                            <div class="input-group">
                                <input class="form-control" id="key" name="key">
                            </div>
                            @if($errors->has('key'))
                                <div class="text-danger">{{$errors->first('key')}}</div>
                            @endif
                        </div>

                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="name">{{translate('languages.name')}}</label>
                            <div class="input-group">
                                <input class="form-control" id="name" name="name">
                            </div>
                            @if($errors->has('name'))
                                <div class="text-danger">{{$errors->first('name')}}</div>
                            @endif
                        </div>

                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="description">{{translate('languages.description')}}</label>
                            <div class="input-group">
                                <input class="form-control" id="description" name="description">
                            </div>
                            @if($errors->has('description'))
                                <div class="text-danger">{{$errors->first('description')}}</div>
                            @endif
                        </div>

                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="order">{{translate('languages.order')}}</label>
                            <div class="input-group">
                                <input class="form-control" id="order" name="order" value="{{getLastOrder('languages')}}">
                            </div>
                            @if($errors->has('order'))
                                <div class="text-danger">{{$errors->first('order')}}</div>
                            @endif
                        </div>

                    </div>


                </div>
                <div class="card-footer">
                    <div class="text-right">
                        <button class="btn bg-slate submitAJAX">{{translate('languages.addNewLanguage')}}</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

@endsection

@section('scripts')
    <script>
        $(function(){
            $('select.select2').select2();
        });
    </script>
@endsection

resources/views/admin/languages/edit.blade.php
@extends('admin.layouts.layout')


@section('styles')
    <style>
        #roles tr, #roles td, #roles th{
            border:1px solid #ebebeb;
            padding: 10px;
        }
        #infos .row {
            border-bottom: 1px solid #ebebeb;
            margin: 10px 0;
        }
        #infos .row:last-child {
            border-bottom: 0;
        }
        .select2-selection--multiple .select2-search--inline:first-child .select2-search__field {
            padding-left: .5rem;
        }
    </style>
@endsection

@section('content')

    <!-- Page header -->
    <div class="page-header page-header-light" style="border-left: 1px solid #ddd; border-right: 1px solid #ddd;">

        <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline py-2">
            <div class="d-flex">
                <div class="breadcrumb">
                    <a href="{{route('admin.dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> {{translate('breadcrumb.dashboard')}}</a>
                    <a href="{{route('admin.languages.index')}}" class="breadcrumb-item">{{translate('breadcrumb.languages')}}</a>
                    <span class="breadcrumb-item active">{{$language['name']}}</span>
                </div>
            </div>
        </div>
    </div>
    <!-- /page header -->

    <div class="content p-0">
        <form action="{{route('admin.languages.update',['language' => $language['id']])}}" method="post" data-reload="reload">
            @csrf
            @method('PUT')
            <div class="card border-top-0 mb-0">
                @if(session()->has('success'))
                    {!! alert(session()->get('success')) !!}
                @endif
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="key">{{translate('languages.key')}}</label>
                            <div class="input-group">
                                <input class="form-control" id="key" name="key" value="{{$language['key']}}">
                            </div>
                            @if($errors->has('key'))
                                <div class="text-danger">{{$errors->first('key')}}</div>
                            @endif
                        </div>

                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="name">{{translate('languages.name')}}</label>
                            <div class="input-group">
                                <input class="form-control" id="name" name="name" value="{{$language['name']}}">
                            </div>
                            @if($errors->has('name'))
                                <div class="text-danger">{{$errors->first('name')}}</div>
                            @endif
                        </div>

                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="description">{{translate('languages.description')}}</label>
                            <div class="input-group">
                                <input class="form-control" id="description" name="description" value="{{$language['description']}}">
                            </div>
                            @if($errors->has('description'))
                                <div class="text-danger">{{$errors->first('description')}}</div>
                            @endif
                        </div>

                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="order">{{translate('languages.order')}}</label>
                            <div class="input-group">
                                <input class="form-control" id="order" name="order" value="{{$language['order']}}">
                            </div>
                            @if($errors->has('order'))
                                <div class="text-danger">{{$errors->first('order')}}</div>
                            @endif
                        </div>

                        <div class="form-group col-lg-12 col-md-12 col-sm-12">
                            <label for="status">{{translate('languages.status')}}</label>
                            <div class="input-group">
                                <input class="form-control switchery" id="status" type="checkbox" name="status" {{$language['status']?'checked':''}}>
                            </div>
                        </div>

                    </div>


                </div>
                <div class="card-footer">
                    <div class="text-right">
                        <button class="btn bg-slate submitAJAX">{{translate('languages.editLanguage')}}</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

@endsection

@section('scripts')
    <script>
        $(function(){
            $('select.select2').select2();
        });
    </script>
@endsection

resources/views/admin/languages/index.blade.php
@extends('admin.layouts.layout')


@section('styles')
    <style>
        #roles tr, #roles td, #roles th{
            border:1px solid #ebebeb;
            padding: 10px;
        }
    </style>
@endsection

@section('content')

    <div class="page-header page-header-light" style="border-left: 1px solid #ddd; border-right: 1px solid #ddd;">

        <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline py-2">
            <div class="d-flex">
                <div class="breadcrumb">
                    <a href="{{route('admin.dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> {{translate('breadcrumb.dashboard')}}</a>
                    <span class="breadcrumb-item active">{{translate('breadcrumb.languages')}}</span>
                </div>
            </div>
            @permission('create-languages')
            <div class="text-right">
                <a href="{{route('admin.languages.create')}}" class="btn btn-labeled btn-labeled-right bg-slate addData">{{translate('breadcrumb.addLanguage')}} <b><i class="icon-plus2"></i></b></a>
            </div>
            @endpermission
        </div>
    </div>
    <!-- /page header -->
    <div class="content p-0">
        <div class="card border-top-0">
            <div class="card-header d-none">
            </div>

            @if(session()->has('success'))
                {!! alert(session()->get('success')) !!}
            @endif
            <div class="card-body">
                <table class="table datatable-order dataTable no-footer" data-model="languages" width="100%">
                    <thead>
                        <tr>
                            @permission('delete-languages')
                                <th class="no-sort sorting_disabled" style="width: 20px;"><input type="checkbox" class="selectAll form-check-input-styled" data-target="selecteds"></th>
                            @endpermission
                            <th style="width: 100px">ID</th>
                            <th>{{translate('table.key')}}</th>
                            <th>{{translate('table.name')}}</th>
                            <th>{{translate('table.description')}}</th>
                            <th>{{translate('table.order')}}</th>
                            <th>{{translate('table.status')}}</th>
                            @permission('update-languages|delete-languages')
                                <th class="text-center no-sort" style="width: 100px">{{translate('table.actions')}}</th>
                            @endpermission
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($languages as $language)
                            <tr>
                                @permission('delete-languages')
                                    <td><input type="checkbox" class="form-check-input-styled" name="selecteds" value="{{$language['id']}}"></td>
                                @endpermission
                                <td>{{$language['id']}}</td>
                                <td>{{$language['key']}}</td>
                                <td>{{$language['name']}}</td>
                                <td>{{$language['description']}}</td>
                                <td>{{$language['order']}}</td>
                                <td>{!! getStatus($language['status']) !!}</td>
                                @permission('update-languages|delete-languages')
                                    <td class="text-center">
                                        <div class="list-icons">
                                            @permission('update-languages')
                                                <a href="{{route('admin.languages.edit',['language' => $language['id']])}}" class="dropdown-item mr-0 editData"><i class="icon-pencil mr-0 text-slate"></i> </a>
                                            @endpermission
                                            @permission('delete-languages')
                                                <a data-false class="dropdown-item mr-0 delete" data-model="languages" data-type="language" data-id="{{$language['id']}}"><i class="icon-bin mr-0 text-danger"></i> </a>
                                            @endpermission
                                        </div>
                                    </td>
                                @endpermission
                            </tr>
                        @endforeach
                    </tbody>
                    @permission('delete-languages')
                        <tfoot>
                            <tr>
                                <td style="padding: .75rem 0;" colspan="8"><button class="btn btn-danger btn-labeled btn-labeled-right deleteAll" disabled><span>{{translate('common.delete')}}</span><b><i class="icon-bin"></i></b></button></td>
                            </tr>
                        </tfoot>
                    @endpermission
                </table>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script>
        $(function(){
            $('.datatable-order').table(4);
        });
    </script>
@endsection