routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*********************Front**********************/

Auth::routes(['register' => false]);

Route::get('/', 'HomeController@index')->name('home');
Route::get('/page/{slug}-{id}', 'HomeController@page')->name('page')->where(['slug' => '[A-Za-z0-9_\-]+','id' => '\d+']);
Route::get('/offers/{slug}-{offer_id}', 'HomeController@offers')->name('offers')->where(['slug' => '[A-Za-z0-9_\-]+','id' => '\d+']);
Route::get('/leaflets', 'HomeController@leaflet')->name('leaflet');
Route::get('/leaflets/{slug}', 'HomeController@leafletGet')->name('leaflet.Get');

Route::post('/form/ad', 'BravoFormController@addReklamForm')->name('form.ad');
Route::post('/form/media', 'BravoFormController@addMediaForm')->name('form.media');
Route::post('/form/b2b', 'BravoFormController@addB2bForm')->name('form.b2b');
Route::post('/form/supplier', 'BravoFormController@addSupplierForm')->name('form.supplier');
Route::post('/form/contact_feedback', 'BravoFormController@addContactFeedback')->name('form.contact_feedback');
Route::post('/form/customer_feedback', 'BravoFormController@addCustomerFeedback')->name('form.customer_feedback');


Route::get('/language/{language?}', 'HomeController@setLocale')->name('setLocale');

Route::group(['prefix' => 'career', 'as' => 'career.'],function (){
    Route::get('/', 'CareerController@index')->name('index');
    Route::get('/apply', 'CareerController@applyGet')->name('applyGet');
    Route::post('/apply', 'CareerController@applyStore')->name('applyStore');
});

Route::get('/cards', 'HomeController@card')->name('card');
Route::get('/page/students/{group_id}', 'HomeController@getStudentsWithGroup')->name('get.students.group');

Route::get('/v1/api/stores', 'HomeController@getAllStores')->name('api.stores');
Route::get('/v1/api/store/{id}', 'HomeController@getStoreById')->name('api.store');
Route::get('/v1/api/search/store', 'HomeController@searchStore')->name('api.store.search');



/*********************Panel**********************/
Route::group(['prefix' => 'admin', 'middleware' => ['auth','lang'], 'as' => 'admin.'],function(){
    Route::get('/', 'AdminController@index')->name('dashboard');



    //Rauf Abbas
    Route::delete('/vacancies/deleteSelecteds', 'BannerController@destroySelecteds');
    Route::resource('/vacancies', 'VacancyController');
    Route::get('/vacancies/export/{id}', 'VacancyController@export')->name('vacancies.export');

    Route::delete('/cards/deleteSelecteds', 'CardController@destroySelecteds');
    Route::resource('/cards', 'CardController');

    Route::delete('/stores/deleteSelecteds', 'StoreController@destroySelecteds');
    Route::resource('/stores', 'StoreController');

    Route::delete('/students/deleteSelecteds', 'StudentController@destroySelecteds');
    Route::resource('/students', 'StudentController');


    Route::resource('/leaflets', 'LeafletController');
    Route::delete('/leaflets/deleteSelecteds', 'LeafletController@destroySelecteds');


    Route::delete('/categories/deleteSelecteds', 'CategoryController@destroySelecteds');
    Route::resource('/categories', 'CategoryController');

    Route::delete('/posts/deleteSelecteds', 'PostController@destroySelecteds');
    Route::resource('/posts', 'PostController');

    Route::resource('/tabs/deleteSelecteds', 'TabController@destroySelecteds');
    Route::resource('/tabs', 'TabController');

    Route::delete('/faqs/deleteSelecteds', 'FaqController@destroySelecteds');
    Route::resource('/faqs', 'FaqController');

    Route::delete('/menus/deleteSelecteds', 'MenuController@destroySelecteds');
    Route::resource('/menus', 'MenuController');

    Route::delete('/pages/deleteSelecteds', 'PageController@destroySelecteds');
    Route::resource('/pages', 'PageController');

    Route::delete('/sliders/deleteSelecteds', 'SliderController@destroySelecteds');
    Route::resource('/sliders', 'SliderController');

    Route::delete('/banners/deleteSelecteds', 'BannerController@destroySelecteds');
    Route::resource('/banners', 'BannerController');

    Route::delete('/offers/deleteSelecteds', 'OfferController@destroySelecteds');
    Route::resource('/offers', 'OfferController');

    Route::delete('/offers/deleteSelecteds', 'OfferProductController@destroySelecteds');
    Route::resource('/offer-products', 'OfferProductController');

    Route::delete('/users/deleteSelecteds', 'UserController@destroySelecteds');
    Route::resource('/users', 'UserController');

    Route::delete('/roles/deleteSelecteds', 'RoleController@destroySelecteds');
    Route::resource('/roles', 'RoleController');

    Route::delete('/permissions/deleteSelecteds', 'PermissionController@destroySelecteds');
    Route::resource('/permissions', 'PermissionController');

    Route::delete('/languages/deleteSelecteds', 'LanguageController@destroySelecteds');
    Route::resource('/languages', 'LanguageController');

    Route::get('/translation_group/{translation_group}/translations', 'TranslationGroupController@translations')->name('translation_group.translations');
    Route::delete('/translation_groups/deleteSelecteds', 'TranslationGroupController@destroySelecteds');
    Route::resource('/translation_groups', 'TranslationGroupController');

    Route::get('/translations/exportView', 'TranslationController@exportView')->name('translations.exportView');
    Route::get('/translations/export', 'TranslationController@export')->name('translations.export');
    Route::get('/translations/create/{group?}', 'TranslationController@create');
    Route::delete('/translations/deleteSelecteds', 'TranslationController@destroySelecteds');
    Route::resource('/translations', 'TranslationController');

    Route::post('/mediaUpload', 'AdminController@mediaUpload')->name('mediaUpload');
    Route::post('/generateSlug', 'AdminController@generateSlug')->name('generateSlug');
    Route::post('/generateOrderNumberInParent', 'AdminController@generateOrderNumberInParent')->name('generateOrderNumberInParent');
    Route::post('/reorder', 'AdminController@reorder')->name('reorder');

    Route::get('/config', 'AdminController@index')->name('config');
    Route::get('/site', 'AdminController@index')->name('site');

    Route::get('/requests/{type}', 'BravoFormController@getAdminPanel')->name('requests.index');
});

app/TranslationGroup.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class TranslationGroup extends Model
{
    public function translations(){
        return $this->hasMany('\App\Translation','group_id','id');
    }
}

app/Http/Controllers/TranslationGroupController.php
<?php

namespace App\Http\Controllers;

use App\TranslationGroup;
use Illuminate\Http\Request;

class TranslationGroupController extends Controller
{

    public function __construct()
    {
        $this->middleware('permission:create-translation-groups', ['only' => ['create', 'store']]);
        $this->middleware('permission:read-translation-groups'  , ['only' => ['index']]);
        $this->middleware('permission:update-translation-groups', ['only' => ['edit','update']]);
        $this->middleware('permission:delete-translation-groups', ['only' => ['destroy','destroySelecteds']]);
    }

    public function index()
    {
        $translation_groups = TranslationGroup::all();
        return view('admin.translation_groups.index')->with(compact('translation_groups'));
    }


    public function create()
    {
        return view('admin.translation_groups.create');
    }


    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|unique:translation_groups',
            'description' => 'required|string',
        ]);

        $translation_group = new TranslationGroup();
        $translation_group->name = $request->name;
        $translation_group->description = $request->description;
        $translation_group->save();

        $data = [
            'status'    => 'success',
            'message'   => "Translation group - <span class='font-weight-semibold'>{$translation_group->name}</span> is created successfully"
        ];
        return response()->json($data,200);
    }


    public function show(TranslationGroup $translationGroup)
    {
        //
    }

    public function translations(TranslationGroup $translationGroup){
        $translations = $translationGroup->translations()->get();
        $data = [];
        foreach ($translations as $translation){
            $translation->translationGroup = $translation->group->name;
//            dd($translation);
            $translationValue = json_decode($translation->value,1);
            $translationValue = $translationValue[getLocale()] ?? "{$translation->translationGroup}.{$translation->key}";
            $translation->value = $translationValue;
            unset($translation->group);
            $data[] = $translation;
        }
        return response()->json($data,200,[],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
    }


    public function edit(TranslationGroup $translation_group)
    {
        return view('admin.translation_groups.edit')->with(compact('translation_group'));
    }

    public function update(Request $request, TranslationGroup $translation_group)
    {
        $request->validate([
            'name' => 'required|string',
            'description' => 'required|string',
        ]);

        $oldData = $translation_group->name;
        $translation_group->name = $request->name;
        $translation_group->description = $request->description;
        $translation_group->status = $request->status?true:false;
        $translation_group->save();

        $data = [
            'status'    => 'success',
            'message'   => "Translation group - <span class='font-weight-semibold'>{$oldData}</span> is updated successfully"
        ];
        return response()->json($data,200);
    }


    public function destroy(TranslationGroup $translation_group)
    {
        $oldData = $translation_group->name;
        $translation_group->delete();

        $data = [
            'status'    => 'success',
            'message'   => "Translation Group - <span class='font-weight-semibold'>{$oldData}</span> is deleted successfully!"
        ];
        return response()->json($data,200);
    }

    public function destroySelecteds(Request $request)
    {
        foreach ($request->selecteds as $selected) {
            $deleteData = TranslationGroup::findOrFail($selected);
            $deleteData->delete();
        }

        $data = [
            'status'    => 'success',
            'message'   => "Selected <span class='font-weight-semibold'>translation groups</span> are deleted successfully!"
        ];
        return response()->json($data,200);
    }
}

resources/views/admin/translation_groups/create.blade.php
@extends('admin.layouts.layout')


@section('styles')
    <style>
        #roles tr, #roles td, #roles th{
            border:1px solid #ebebeb;
            padding: 10px;
        }
        #infos .row {
            border-bottom: 1px solid #ebebeb;
            margin: 10px 0;
        }
        #infos .row:last-child {
            border-bottom: 0;
        }
        .select2-selection--multiple .select2-search--inline:first-child .select2-search__field {
            padding-left: .5rem;
        }
    </style>
@endsection

@section('content')

    <!-- Page header -->
    <div class="page-header page-header-light" style="border-left: 1px solid #ddd; border-right: 1px solid #ddd;">

        <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline py-2">
            <div class="d-flex">
                <div class="breadcrumb">
                    <a href="{{route('admin.dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> {{translate('breadcrumb.dashboard')}}</a>
                    <a href="{{route('admin.translation_groups.index')}}" class="breadcrumb-item">{{translate('breadcrumb.translationGroups')}}</a>
                    <span class="breadcrumb-item active">{{translate('breadcrumb.newTranslationGroup')}}</span>
                </div>
            </div>
        </div>
    </div>
    <!-- /page header -->

    <div class="content p-0">
        <form action="{{route('admin.translation_groups.store')}}" method="post" data-reload="reload">
            @csrf
            <div class="card border-top-0 mb-0">
                <div class="card-body">
                    <div class="row">

                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="name">{{translate('translationGroups.name')}}</label>
                            <div class="input-group">
                                <input class="form-control" id="name" name="name">
                            </div>
                            @if($errors->has('name'))
                                <div class="text-danger">{{$errors->first('name')}}</div>
                            @endif
                        </div>

                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="description">{{translate('translationGroups.description')}}</label>
                            <div class="input-group">
                                <input class="form-control" id="description" name="description">
                            </div>
                            @if($errors->has('description'))
                                <div class="text-danger">{{$errors->first('description')}}</div>
                            @endif
                        </div>

                    </div>


                </div>
                <div class="card-footer">
                    <div class="text-right">
                        <button class="btn bg-slate submitAJAX">{{translate('translationGroups.addTranslationGroup')}}</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

@endsection

@section('scripts')
    <script>
        $(function(){
            $('select.select2').select2();
        });
    </script>
@endsection

resources/views/admin/translation_groups/edit.blade.php
@extends('admin.layouts.layout')


@section('styles')
    <style>
        #roles tr, #roles td, #roles th{
            border:1px solid #ebebeb;
            padding: 10px;
        }
        #infos .row {
            border-bottom: 1px solid #ebebeb;
            margin: 10px 0;
        }
        #infos .row:last-child {
            border-bottom: 0;
        }
        .select2-selection--multiple .select2-search--inline:first-child .select2-search__field {
            padding-left: .5rem;
        }
    </style>
@endsection

@section('content')

    <!-- Page header -->
    <div class="page-header page-header-light" style="border-left: 1px solid #ddd; border-right: 1px solid #ddd;">

        <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline py-2">
            <div class="d-flex">
                <div class="breadcrumb">
                    <a href="{{route('admin.dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> {{translate('breadcrumb.dashboard')}}</a>
                    <a href="{{route('admin.translation_groups.index')}}" class="breadcrumb-item">{{translate('breadcrumb.translationGroups')}}</a>
                    <span class="breadcrumb-item active">{{$translation_group['name']}}</span>
                </div>
            </div>
        </div>
    </div>
    <!-- /page header -->

    <div class="content p-0">
        <form action="{{route('admin.translation_groups.update',['translation_group' => $translation_group['id']])}}" method="post" data-reload="reload">
            @csrf
            @method('PUT')
            <div class="card border-top-0 mb-0">
                @if(session()->has('success'))
                    {!! alert(session()->get('success')) !!}
                @endif
                <div class="card-body">
                    <div class="row">

                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="name">{{translate('translationGroups.name')}}</label>
                            <div class="input-group">
                                <input class="form-control" id="name" name="name" value="{{$translation_group['name']}}">
                            </div>
                            @if($errors->has('name'))
                                <div class="text-danger">{{$errors->first('name')}}</div>
                            @endif
                        </div>

                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="description">{{translate('translationGroups.description')}}</label>
                            <div class="input-group">
                                <input class="form-control" id="description" name="description" value="{{$translation_group['description']}}">
                            </div>
                            @if($errors->has('description'))
                                <div class="text-danger">{{$errors->first('description')}}</div>
                            @endif
                        </div>

                        <div class="form-group col-lg-12 col-md-12 col-sm-12">
                            <label for="status">{{translate('translationGroups.status')}}</label>
                            <div class="input-group">
                                <input class="form-control switchery" id="status" type="checkbox" name="status" {{$translation_group['status']?'checked':''}}>
                            </div>
                        </div>

                    </div>


                </div>
                <div class="card-footer">
                    <div class="text-right">
                        <button class="btn bg-slate submitAJAX">{{translate('translationGroups.editTranslationGroup')}}</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

@endsection

@section('scripts')
    <script>
        $(function(){
            $('select.select2').select2();
        });
    </script>
@endsection

resources/views/admin/translation_groups/index.blade.php
@extends('admin.layouts.layout')


@section('styles')
    <style>
        #roles tr, #roles td, #roles th{
            border:1px solid #ebebeb;
            padding: 10px;
        }
    </style>
@endsection

@section('content')

    <div class="page-header page-header-light" style="border-left: 1px solid #ddd; border-right: 1px solid #ddd;">

        <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline py-2">
            <div class="d-flex">
                <div class="breadcrumb">
                    <a href="{{route('admin.dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> {{translate('breadcrumb.dashboard')}}</a>
                    <span class="breadcrumb-item active">{{translate('breadcrumb.translationGroups')}}</span>
                </div>
            </div>
            @permission('create-translation-groups')
                <div class="text-right">
                    <a href="{{route('admin.translation_groups.create')}}" class="btn btn-labeled btn-labeled-right bg-slate addData">{{translate('breadcrumb.addTranslationGroup')}} <b><i class="icon-plus2"></i></b></a>
                </div>
            @endpermission
        </div>
    </div>
    <!-- /page header -->
    <div class="content p-0">
        <div class="card border-top-0">
            <div class="card-header d-none">
            </div>

            @if(session()->has('success'))
                {!! alert(session()->get('success')) !!}
            @endif
            <div class="card-body">
                <table class="table datatable-basic dataTable no-footer" data-model="translation_groups" width="100%">
                    <thead>
                        <tr>
                            @permission('delete-translation-groups')
                                <th class="no-sort sorting_disabled" style="width: 20px;"><input type="checkbox" class="selectAll form-check-input-styled" data-target="selecteds"></th>
                            @endpermission
                            <th style="width: 100px">ID</th>
                            <th>{{translate('table.name')}}</th>
                            <th>{{translate('table.description')}}</th>
                            <th>{{translate('table.status')}}</th>
                            @permission('update-translation-groups|delete-translation-groups')
                                <th class="text-center no-sort" style="width: 100px">{{translate('table.actions')}}</th>
                            @endpermission
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($translation_groups as $translation_group)
                            <tr>
                                @permission('delete-translation-groups')
                                    <td><input type="checkbox" class="form-check-input-styled" name="selecteds" value="{{$translation_group['id']}}"></td>
                                @endpermission
                                <td>{{$translation_group['id']}}</td>
                                <td>{{$translation_group['name']}}</td>
                                <td>{{$translation_group['description']}}</td>
                                <td>{!! getStatus($translation_group['status']) !!}</td>
                                @permission('update-translation-groups|delete-translation-groups')
                                    <td class="text-center">
                                        <div class="list-icons">
                                            @permission('update-translation-groups')
                                                <a href="{{route('admin.translation_groups.edit',['translation_group' => $translation_group['id']])}}" class="dropdown-item mr-0 editData"><i class="icon-pencil mr-0 text-slate"></i> </a>
                                            @endpermission
                                            @permission('delete-translation-groups')
                                                <a data-false class="dropdown-item mr-0 delete" data-model="translation_groups" data-type="translation group" data-id="{{$translation_group['id']}}"><i class="icon-bin mr-0 text-danger"></i> </a>
                                            @endpermission
                                        </div>
                                    </td>
                                @endpermission
                            </tr>
                        @endforeach
                    </tbody>
                    @permission('delete-translation-groups')
                        <tfoot>
                            <tr>
                                <td style="padding: .75rem 0;" colspan="6"><button class="btn btn-danger btn-labeled btn-labeled-right deleteAll" disabled><span>{{translate('common.delete')}}</span><b><i class="icon-bin"></i></b></button></td>
                            </tr>
                        </tfoot>
                    @endpermission
                </table>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script>

    </script>
@endsection