routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*********************Front**********************/

Auth::routes(['register' => false]);

Route::get('/', 'HomeController@index')->name('home');
Route::get('/page/{slug}-{id}', 'HomeController@page')->name('page')->where(['slug' => '[A-Za-z0-9_\-]+','id' => '\d+']);
Route::get('/offers/{slug}-{offer_id}', 'HomeController@offers')->name('offers')->where(['slug' => '[A-Za-z0-9_\-]+','id' => '\d+']);
Route::get('/leaflets', 'HomeController@leaflet')->name('leaflet');
Route::get('/leaflets/{slug}', 'HomeController@leafletGet')->name('leaflet.Get');

Route::post('/form/ad', 'BravoFormController@addReklamForm')->name('form.ad');
Route::post('/form/media', 'BravoFormController@addMediaForm')->name('form.media');
Route::post('/form/b2b', 'BravoFormController@addB2bForm')->name('form.b2b');
Route::post('/form/supplier', 'BravoFormController@addSupplierForm')->name('form.supplier');
Route::post('/form/contact_feedback', 'BravoFormController@addContactFeedback')->name('form.contact_feedback');
Route::post('/form/customer_feedback', 'BravoFormController@addCustomerFeedback')->name('form.customer_feedback');


Route::get('/language/{language?}', 'HomeController@setLocale')->name('setLocale');

Route::group(['prefix' => 'career', 'as' => 'career.'],function (){
    Route::get('/', 'CareerController@index')->name('index');
    Route::get('/apply', 'CareerController@applyGet')->name('applyGet');
    Route::post('/apply', 'CareerController@applyStore')->name('applyStore');
});

Route::get('/cards', 'HomeController@card')->name('card');
Route::get('/page/students/{group_id}', 'HomeController@getStudentsWithGroup')->name('get.students.group');

Route::get('/v1/api/stores', 'HomeController@getAllStores')->name('api.stores');
Route::get('/v1/api/store/{id}', 'HomeController@getStoreById')->name('api.store');
Route::get('/v1/api/search/store', 'HomeController@searchStore')->name('api.store.search');



/*********************Panel**********************/
Route::group(['prefix' => 'admin', 'middleware' => ['auth','lang'], 'as' => 'admin.'],function(){
    Route::get('/', 'AdminController@index')->name('dashboard');



    //Rauf Abbas
    Route::delete('/vacancies/deleteSelecteds', 'BannerController@destroySelecteds');
    Route::resource('/vacancies', 'VacancyController');
    Route::get('/vacancies/export/{id}', 'VacancyController@export')->name('vacancies.export');

    Route::delete('/cards/deleteSelecteds', 'CardController@destroySelecteds');
    Route::resource('/cards', 'CardController');

    Route::delete('/stores/deleteSelecteds', 'StoreController@destroySelecteds');
    Route::resource('/stores', 'StoreController');

    Route::delete('/students/deleteSelecteds', 'StudentController@destroySelecteds');
    Route::resource('/students', 'StudentController');


    Route::resource('/leaflets', 'LeafletController');
    Route::delete('/leaflets/deleteSelecteds', 'LeafletController@destroySelecteds');


    Route::delete('/categories/deleteSelecteds', 'CategoryController@destroySelecteds');
    Route::resource('/categories', 'CategoryController');

    Route::delete('/posts/deleteSelecteds', 'PostController@destroySelecteds');
    Route::resource('/posts', 'PostController');

    Route::resource('/tabs/deleteSelecteds', 'TabController@destroySelecteds');
    Route::resource('/tabs', 'TabController');

    Route::delete('/faqs/deleteSelecteds', 'FaqController@destroySelecteds');
    Route::resource('/faqs', 'FaqController');

    Route::delete('/menus/deleteSelecteds', 'MenuController@destroySelecteds');
    Route::resource('/menus', 'MenuController');

    Route::delete('/pages/deleteSelecteds', 'PageController@destroySelecteds');
    Route::resource('/pages', 'PageController');

    Route::delete('/sliders/deleteSelecteds', 'SliderController@destroySelecteds');
    Route::resource('/sliders', 'SliderController');

    Route::delete('/banners/deleteSelecteds', 'BannerController@destroySelecteds');
    Route::resource('/banners', 'BannerController');

    Route::delete('/offers/deleteSelecteds', 'OfferController@destroySelecteds');
    Route::resource('/offers', 'OfferController');

    Route::delete('/offers/deleteSelecteds', 'OfferProductController@destroySelecteds');
    Route::resource('/offer-products', 'OfferProductController');

    Route::delete('/users/deleteSelecteds', 'UserController@destroySelecteds');
    Route::resource('/users', 'UserController');

    Route::delete('/roles/deleteSelecteds', 'RoleController@destroySelecteds');
    Route::resource('/roles', 'RoleController');

    Route::delete('/permissions/deleteSelecteds', 'PermissionController@destroySelecteds');
    Route::resource('/permissions', 'PermissionController');

    Route::delete('/languages/deleteSelecteds', 'LanguageController@destroySelecteds');
    Route::resource('/languages', 'LanguageController');

    Route::get('/translation_group/{translation_group}/translations', 'TranslationGroupController@translations')->name('translation_group.translations');
    Route::delete('/translation_groups/deleteSelecteds', 'TranslationGroupController@destroySelecteds');
    Route::resource('/translation_groups', 'TranslationGroupController');

    Route::get('/translations/exportView', 'TranslationController@exportView')->name('translations.exportView');
    Route::get('/translations/export', 'TranslationController@export')->name('translations.export');
    Route::get('/translations/create/{group?}', 'TranslationController@create');
    Route::delete('/translations/deleteSelecteds', 'TranslationController@destroySelecteds');
    Route::resource('/translations', 'TranslationController');

    Route::post('/mediaUpload', 'AdminController@mediaUpload')->name('mediaUpload');
    Route::post('/generateSlug', 'AdminController@generateSlug')->name('generateSlug');
    Route::post('/generateOrderNumberInParent', 'AdminController@generateOrderNumberInParent')->name('generateOrderNumberInParent');
    Route::post('/reorder', 'AdminController@reorder')->name('reorder');

    Route::get('/config', 'AdminController@index')->name('config');
    Route::get('/site', 'AdminController@index')->name('site');

    Route::get('/requests/{type}', 'BravoFormController@getAdminPanel')->name('requests.index');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function posts(){
        return $this->hasMany('\App\Post','category_id','id');
    }

    public static function getCategories($onlyActives = false)
    {
        $data = [];
        $categories = Category::where('parent_id',null);
        if($onlyActives){
            $categories = $categories->where('status',true);
        }
        $categories = $categories->orderBy('order','asc')->get();
        foreach ($categories as $category){
            if(!Category::hasSubCategories($category->id)){
                $data[] = $category;
            }else{
                $subCategories = Category::getSubCategories($category->id);
                $category->subcategories = $subCategories;
                $data[] = $category;
            }

        }
        return $data;
    }

    public static function hasSubCategories($category_id){
        return Category::where('parent_id',$category_id)->count();
    }

    public static function getSubCategories($category_id)
    {
        $data = [];
        $subCategories = Category::where('parent_id',$category_id)->orderBy('order','asc')->get();
        foreach ($subCategories as $subCategory){
            if(!Category::hasSubCategories($subCategory->id)){
                $data[] = $subCategory;
            }else{
                $subCategories = Category::getSubCategories($subCategory->id);
                $subCategory->subcategories = $subCategories;
                $data[] = $subCategory;
            }

        }
        return $data;
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:create-categories', ['only' => ['create', 'store']]);
        $this->middleware('permission:read-categories'  , ['only' => ['index']]);
        $this->middleware('permission:update-categories', ['only' => ['edit','update']]);
        $this->middleware('permission:delete-categories', ['only' => ['destroy','destroySelecteds']]);
    }
    public function index()
    {
        $categories = Category::getCategories();
        return view('admin.categories.index')->with(compact('categories'));
    }


    public function create()
    {
        $categories = Category::getCategories();
        return view('admin.categories.create')->with(compact('categories'));
    }


    public function store(Request $request)
    {
        $request->validate([
            'parent_id' => 'required|string|nullable',
            'name' => 'required|string|unique:categories',
            'description' => 'required|string',
            'order' => 'required|integer',
        ]);

        $category = new Category();
        $category->parent_id = $request->parent_id==='null'?null:$request->parent_id;
        $category->name = $request->name;
        $category->description = $request->description;
        $category->order = $request->order;
        $category->save();

        $data = [
            'status'    => 'success',
            'message'   => "Category - <span class='font-weight-semibold'>{$category->name}</span> is created successfully!"
        ];
        return response()->json($data,200);
    }


    public function show($id)
    {
        //
    }


    public function edit(Category $category)
    {
        $categories = Category::getCategories();
        return view('admin.categories.edit')->with(compact('category','categories'));
    }


    public function update(Request $request, Category $category)
    {
        $request->validate([
            'parent_id' => 'required|string|nullable',
            'name' => 'required|string',
            'description' => 'required|string',
            'order' => 'required|integer'
        ]);

        $oldData = $category->name;
        $category->parent_id = $request->parent_id==='null'?null:$request->parent_id;
        $category->name = $request->name;
        $category->description = $request->description;
        $category->order = $request->order;
        $category->status = $request->status?true:false;
        $category->save();

        $data = [
            'status'    => 'success',
            'message'   => "Category - <span class='font-weight-semibold'>{$oldData}</span> is updated successfully!"
        ];
        return response()->json($data,200);
    }


    public function destroy(Category $category)
    {
        $oldData = $category->name;
        $category->delete();

        $data = [
            'status'    => 'success',
            'message'   => "Category - <span class='font-weight-semibold'>{$oldData}</span> is deleted successfully!"
        ];
        return response()->json($data,200);
    }

    public function destroySelecteds(Request $request)
    {
        foreach ($request->selecteds as $selected) {
            $deleteData = Category::findOrFail($selected);
            $deleteData->delete();
        }

        $data = [
            'status'    => 'success',
            'message'   => "Selected <span class='font-weight-semibold'>categories</span> are deleted successfully!"
        ];
        return response()->json($data,200);
    }


}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.layout')


@section('styles')
    <style>
        #roles tr, #roles td, #roles th{
            border:1px solid #ebebeb;
            padding: 10px;
        }
        #infos .row {
            border-bottom: 1px solid #ebebeb;
            margin: 10px 0;
        }
        #infos .row:last-child {
            border-bottom: 0;
        }
        .select2-selection--multiple .select2-search--inline:first-child .select2-search__field {
            padding-left: .5rem;
        }
    </style>
@endsection

@section('content')

    <!-- Page header -->
    <div class="page-header page-header-light" style="border-left: 1px solid #ddd; border-right: 1px solid #ddd;">

        <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline py-2">
            <div class="d-flex">
                <div class="breadcrumb">
                    <a href="{{route('admin.dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> {{translate('breadcrumb.dashboard')}}</a>
                    <a href="{{route('admin.categories.index')}}" class="breadcrumb-item">{{translate('breadcrumb.categories')}}</a>
                    <span class="breadcrumb-item active">{{translate('breadcrumb.newCategory')}}</span>
                </div>
            </div>
        </div>
    </div>
    <!-- /page header -->

    <div class="content p-0">
        <form action="{{route('admin.categories.store')}}" method="post" data-reload="reload">
            @csrf
            <div class="card border-top-0 mb-0">
                <div class="card-body">
                    <div class="row">

                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="parent_id">{{translate('categories.parent')}}</label>
                            <div class="input-group">
                                <select class="form-control select2" id="parent_id" name="parent_id">
                                    <option value="null">{{translate('options.noParent')}}</option>
                                    @foreach($categories as $parentCategory)
                                        <option value="{{$parentCategory->id}}">{{$parentCategory->name}}</option>
                                        @if($subcategories = $parentCategory->subcategories)
                                            @include('admin.partials.categories.options', ['subcategories' => $subcategories,'layer' => 1])
                                        @endif
                                    @endforeach
                                </select>
                            </div>
                            @if($errors->has('parent_id'))
                                <div class="text-danger">{{$errors->first('parent_id')}}</div>
                            @endif
                        </div>

                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="name">{{translate('categories.name')}}</label>
                            <div class="input-group">
                                <input class="form-control" id="name" name="name">
                            </div>
                            @if($errors->has('name'))
                                <div class="text-danger">{{$errors->first('name')}}</div>
                            @endif
                        </div>

                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="description">{{translate('categories.description')}}</label>
                            <div class="input-group">
                                <input class="form-control" id="description" name="description">
                            </div>
                            @if($errors->has('description'))
                                <div class="text-danger">{{$errors->first('description')}}</div>
                            @endif
                        </div>

                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="order">{{translate('categories.order')}}</label>
                            <div class="input-group">
                                <input class="form-control" id="order" name="order" value="">
                            </div>
                            @if($errors->has('order'))
                                <div class="text-danger">{{$errors->first('order')}}</div>
                            @endif
                        </div>

                    </div>


                </div>
                <div class="card-footer">
                    <div class="text-right">
                        <button class="btn bg-slate submitAJAX">{{translate('categories.newCategory')}}</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

@endsection

@section('scripts')
    <script>
        $(function(){
            $('select.select2').select2();
            $('#parent_id').trigger('change');
        });
        $(document).on('change','#parent_id',function(){
            let column = 'parent_id';
            let value = $(this).val();
            let model = 'Category';
            pashayev.request({
                url: '{{route('admin.generateOrderNumberInParent')}}',
                input: {column,value,model},
                success: function(response){
                    $('#order').val(response.result.order);
                }
            });
        });
    </script>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.layout')


@section('styles')
    <style>
        #roles tr, #roles td, #roles th{
            border:1px solid #ebebeb;
            padding: 10px;
        }
        #infos .row {
            border-bottom: 1px solid #ebebeb;
            margin: 10px 0;
        }
        #infos .row:last-child {
            border-bottom: 0;
        }
        .select2-selection--multiple .select2-search--inline:first-child .select2-search__field {
            padding-left: .5rem;
        }
    </style>
@endsection

@section('content')

    <!-- Page header -->
    <div class="page-header page-header-light" style="border-left: 1px solid #ddd; border-right: 1px solid #ddd;">

        <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline py-2">
            <div class="d-flex">
                <div class="breadcrumb">
                    <a href="{{route('admin.dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> {{translate('breadcrumb.dashboard')}}</a>
                    <a href="{{route('admin.categories.index')}}" class="breadcrumb-item">{{translate('breadcrumb.categories')}}</a>
                    <span class="breadcrumb-item active">{{$category['name']}}</span>
                </div>
            </div>
        </div>
    </div>
    <!-- /page header -->

    <div class="content p-0">
        <form action="{{route('admin.categories.update',['category' => $category['id']])}}" method="post" data-reload="reload">
            @csrf
            @method('PUT')
            <div class="card border-top-0 mb-0">
                @if(session()->has('success'))
                    {!! alert(session()->get('success')) !!}
                @endif
                <div class="card-body">
                    <div class="row">

                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="parent">{{translate('categories.parent')}}</label>
                            <div class="input-group">
                                <select class="form-control select2" id="parent" name="parent">
                                    <option value="null">{{translate('options.noParent')}}</option>
                                    @foreach($categories as $parentCategory)
                                        <option value="{{$parentCategory->id}}" {{$parentCategory->id===$category->parent?'selected':''}}>{{$parentCategory->name}}</option>
                                        @if($subcategories = $parentCategory->subcategories)
                                            @include('admin.partials.categories.options', ['subcategories' => $subcategories,'layer' => 1,'parent_id' => $category->parent])
                                        @endif
                                    @endforeach
                                </select>
                            </div>
                            @if($errors->has('parent_id'))
                                <div class="text-danger">{{$errors->first('parent_id')}}</div>
                            @endif
                        </div>

                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="name">{{translate('categories.name')}}</label>
                            <div class="input-group">
                                <input class="form-control" id="name" name="name" value="{{$category->name}}">
                            </div>
                            @if($errors->has('name'))
                                <div class="text-danger">{{$errors->first('name')}}</div>
                            @endif
                        </div>


                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="description">{{translate('categories.description')}}</label>
                            <div class="input-group">
                                <input class="form-control" id="description" name="description" value="{{$category->description}}">
                            </div>
                            @if($errors->has('description'))
                                <div class="text-danger">{{$errors->first('description')}}</div>
                            @endif
                        </div>

                        <div class="form-group col-lg-6 col-md-6 col-sm-6">
                            <label for="order">{{translate('categories.order')}}</label>
                            <div class="input-group">
                                <input class="form-control" id="order" name="order" value="{{$category->order}}">
                            </div>
                            @if($errors->has('order'))
                                <div class="text-danger">{{$errors->first('order')}}</div>
                            @endif
                        </div>

                        <div class="form-group col-lg-12 col-md-12 col-sm-12">
                            <label for="status">{{translate('categories.status')}}</label>
                            <div class="input-group">
                                <input class="form-control switchery" id="status" type="checkbox" name="status" {{$category['status']?'checked':''}}>
                            </div>
                        </div>

                    </div>


                </div>
                <div class="card-footer">
                    <div class="text-right">
                        <button class="btn bg-slate submitAJAX">{{translate('categories.editCategory')}}</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

@endsection

@section('scripts')
    <script>
        $(function(){
            $('select.select2').select2();
        });
    </script>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.layout')


@section('styles')
    <style>
        #roles tr, #roles td, #roles th{
            border:1px solid #ebebeb;
            padding: 10px;
        }
        table.dataTable tr.dtrg-group.dtrg-level-0 td {
            background: #607d8b40;
        }
    </style>
@endsection

@section('content')

    <div class="page-header page-header-light" style="border-left: 1px solid #ddd; border-right: 1px solid #ddd;">

        <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline py-2">
            <div class="d-flex">
                <div class="breadcrumb">
                    <a href="{{route('admin.dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> {{translate('breadcrumb.dashboard')}}</a>
                    <span class="breadcrumb-item active">{{translate('breadcrumb.categories')}}</span>
                </div>
            </div>
            @permission('create-categories')
                <div class="text-right">
                    <a href="{{route('admin.categories.create')}}" class="btn btn-labeled btn-labeled-right bg-slate addData">{{translate('breadcrumb.addCategory')}} <b><i class="icon-plus2"></i></b></a>
                </div>
            @endpermission
        </div>
    </div>
    <!-- /page header -->
    <div class="content p-0">
        <div class="card border-top-0">
            <div class="card-header d-none"></div>

            @if(session()->has('success'))
                {!! alert(session()->get('success')) !!}
            @endif
            <div class="card-body">
                <table class="table datatable-basic-no-order dataTable no-footer" data-model="categories" width="100%">
                    <thead>
                        <tr>
                            @permission('delete-categories')
                                <th class="no-sort sorting_disabled" style="width: 20px;"><input type="checkbox" class="selectAll form-check-input-styled" data-target="selecteds"></th>
                            @endpermission
                            <th class="no-sort sorting_disabled" style="width: 100px">ID</th>
                            <th class="no-sort sorting_disabled">{{translate('table.name')}}</th>
                            <th class="no-sort sorting_disabled">{{translate('table.description')}}</th>
                            <th class="no-sort sorting_disabled">{{translate('table.order')}}</th>
                            <th class="no-sort sorting_disabled">{{translate('table.status')}}</th>
                            @permission('update-permissions|delete-categories')
                                <th class="text-center no-sort" style="width: 100px">{{translate('table.actions')}}</th>
                            @endpermission
                        </tr>
                    </thead>
                    <tbody>
                        @php($color = generateHEXColor())
                        @foreach($categories as $category)
                            <tr>
                                @permission('delete-categories')
                                    <td><input type="checkbox" class="form-check-input-styled" name="selecteds" value="{{$category['id']}}"></td>
                                @endpermission
                                <td>{{$category['id']}}</td>
                                <td>{{$category['name']}}</td>
                                <td>{{$category['description']}}</td>
                                <td><span class="p-1 text-white rounded" style="background-color:#{{$color}}">{{$category['order']}}</span></td>
                                <td>{!! getStatus($category['status']) !!}</td>
                                @permission('update-categories|delete-categories')
                                    <td class="text-center">
                                        <div class="list-icons">
                                            @permission('update-categories')
                                                <a href="{{route('admin.categories.edit',['category' => $category['id']])}}" class="dropdown-item mr-0 editData"><i class="icon-pencil mr-0 text-slate"></i> </a>
                                            @endpermission
                                            @permission('delete-categories')
                                                <a data-false class="dropdown-item mr-0 delete" data-model="categories" data-type="category" data-id="{{$category['id']}}"><i class="icon-bin mr-0 text-danger"></i> </a>
                                            @endpermission
                                        </div>
                                    </td>
                                @endpermission
                            </tr>
                            @if($subcategories = $category->subcategories)
                                @include('admin.partials.categories.table', ['subcategories' => $subcategories,'layer' => 1,'existColors' => [$color]])
                            @endif
                        @endforeach
                    </tbody>
                    @permission('delete-categories')
                        <tfoot>
                            <tr>
                                <td style="padding: .75rem 0;" colspan="7"><button class="btn btn-danger btn-labeled btn-labeled-right deleteAll" disabled><span>{{translate('common.delete')}}</span><b><i class="icon-bin"></i></b></button></td>
                            </tr>
                        </tfoot>
                    @endpermission
                </table>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script>

    </script>
@endsection